# Generated by Django 5.0.1 on 2024-04-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='summary',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='city',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='internet_usage',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='profession',
        ),
    ]
