# Generated by Django 5.0.1 on 2024-05-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_anketa'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='gender',
            field=models.CharField(choices=[('M', 'мужской'), ('F', 'женский'), ('unknown', 'unknown')], default='unknown', max_length=7),
        ),
        migrations.AddField(
            model_name='anketa',
            name='internet',
            field=models.CharField(choices=[('daily', 'daily'), ('every_two_days', 'every_two_days'), ('weekly', 'weekly'), ('unknown', 'неизвестно')], default='unknown', max_length=20),
        ),
    ]
