# Generated by Django 5.0.1 on 2024-05-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_anketa_options_remove_anketa_agree_to_news_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anketa',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='anketa',
            name='second_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='gender',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], max_length=1, verbose_name='Пол'),
        ),
    ]
