# Generated by Django 5.0.1 on 2024-05-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_name_anketa_first_name_anketa_second_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anketa',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='internet',
        ),
        migrations.AddField(
            model_name='anketa',
            name='back',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default=5, max_length=1, verbose_name='Хотели бы вы приехать к нам еще?'),
        ),
        migrations.AddField(
            model_name='anketa',
            name='work',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, max_length=1, verbose_name='Оцените качество работы персонала'),
        ),
    ]
