# Generated by Django 5.0.1 on 2024-05-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_anketa_gender_remove_anketa_internet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='reservation',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', max_length=1, verbose_name='Насколько быстро и просто вы забронировали номер?'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='back',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], max_length=1, verbose_name='Хотели бы вы приехать к нам еще?'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ваш город'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Ваш e-mail'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='job',
            field=models.CharField(max_length=100, verbose_name='Ваш род занятий'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='message',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='notice',
            field=models.BooleanField(default=False, verbose_name='Хочу получать новости на электронную почту'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='second_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='work',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', max_length=1, verbose_name='Оцените качество работы персонала'),
        ),
    ]
